name: CI/CD Print App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2 and run script
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
            if [ ! -d ~/my_ci_cd_app ]; then
            git clone https://github.com/VIVEKCHANDAN73/my_ci_cd_app.git ~/my_ci_cd_app
            fi
            cd ~/my_ci_cd_app
            git pull
            python3 main.py > output.txt

